export const GAME = {
  INITIAL_WORLD_WIDTH: 400,
  INITIAL_WORLD_HEIGHT: 700,
  WORLD_EXPAND_STEP: 100,
  WORLD_MAX_WIDTH: 4000,
  WORLD_MAX_HEIGHT: 4000,
  ALIEN_DENSITY_THRESHOLD: 0.00006,
} as const;

export const SPAWN = {
  BUG_BASE_INTERVAL: 1.2,
  BUG_MIN_INTERVAL: 0.15,
  PLANT_BASE_INTERVAL: 6,
  PLANT_MIN_INTERVAL: 1.5,
  MAX_BUGS: 100,
  MAX_PLANTS: 25,
  BUG_COMMON_CHANCE: 0.75,
  BUG_RARE_CHANCE: 0.20,
  BUG_GOLDEN_CHANCE: 0.05,
} as const;

export const ENERGY = {
  BUG_COMMON: 1,
  BUG_RARE: 3,
  BUG_GOLDEN: 10,
  PLANT: 1,
  REWARDED_AD_AMOUNT: 50,
} as const;

export const ALIEN = {
  BASE_SPEED: 60,
  EATING_RANGE: 14,
  EATING_DURATION: 0.4,
  SIZE: 20,
  MAX_ALIENS: 30,
  TURN_RATE: 5,
  BUGS_TO_MATURE: 20,
} as const;

export const COSTS = {
  REPRODUCTION_BASE: 10,
  REPRODUCTION_SCALE: 1.15,
  EATING_CAPACITY_BASE: 25,
  EATING_CAPACITY_SCALE: 1.4,
  SPEED_BASE: 15,
  SPEED_SCALE: 1.3,
  BUG_RATE_BASE: 20,
  BUG_RATE_SCALE: 1.35,
} as const;

export const UPGRADES = {
  EATING_CAPACITY_BOOST: 1,
  SPEED_BOOST: 15,
  BUG_RATE_REDUCTION: 0.85,
} as const;

export const SICKNESS = {
  LIGHT_THRESHOLD: 5,
  MID_THRESHOLD: 20,
  HEAVY_THRESHOLD: 40,
  DEATH_THRESHOLD: 50,
  DISSOLVE_DURATION: 2000,
} as const;

export const ADS = {
  REWARDED_COOLDOWN_MS: 60_000,
  INTERSTITIAL_EVERY_N_REPRODUCTIONS: 5,
} as const;

export const PERSISTENCE = {
  SAVE_KEY: 'idle_alien_tycoon_save',
  SAVE_DEBOUNCE_MS: 5000,
} as const;

export const COLORS = {
  VIVID_HUES: [0, 30, 60, 120, 180, 210, 270, 300, 330],
} as const;

export const GALAXY = {
  BASE_TRAVEL_COST: 500,
  COST_SCALE: 1.5,
  MIN_PLANETS: 3,
  MAX_PLANETS: 8,
  TOTAL_GALAXIES: 100,
} as const;
